/*
 * test_core.c
 *
 * Host tests for the portable core: utilities, HTML/JSON reading, the WPSD
 * parsers and request builders, and the row layout. Reads sample replies
 * generated by mock_wpsd.py --dump-fixtures from the directory in argv[1].
 *
 * Built with ASan/UBSan (see the Makefile), so a parser overrun is a test
 * failure rather than something Rob finds on the RISC OS machine.
 */

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "client.h"
#include "html.h"
#include "scan.h"
#include "json.h"
#include "rows.h"
#include "util.h"
#include "wpsd.h"

static int failures;
static int checks;

static void check_at(const char *file, int line, int ok, const char *expr)
{
    checks++;
    if (!ok) {
        failures++;
        printf("FAIL %s:%d: %s\n", file, line, expr);
    }
}

#define CHECK(c) check_at(__FILE__, __LINE__, (c), #c)

static void check_str_at(const char *file, int line, const char *got,
                         const char *want, const char *expr)
{
    checks++;
    if (strcmp(got, want) != 0) {
        failures++;
        printf("FAIL %s:%d: %s\n   got:  \"%s\"\n   want: \"%s\"\n", file,
               line, expr, got, want);
    }
}

#define CHECK_STR(got, want) check_str_at(__FILE__, __LINE__, (got), (want), #got)

static const char *fixture_dir;

static char *load(const char *name, size_t *len)
{
    char path[512];
    FILE *f;
    char *buf;
    long n;

    snprintf(path, sizeof path, "%s/%s", fixture_dir, name);
    f = fopen(path, "rb");
    if (f == NULL) {
        printf("FAIL cannot open fixture %s\n", path);
        failures++;
        *len = 0;
        return NULL;
    }

    fseek(f, 0, SEEK_END);
    n = ftell(f);
    fseek(f, 0, SEEK_SET);
    buf = (char *)malloc((size_t)n + 1);
    if (fread(buf, 1, (size_t)n, f) != (size_t)n) {
        printf("FAIL short read of %s\n", path);
        failures++;
    }
    buf[n] = '\0';
    fclose(f);
    *len = (size_t)n;
    return buf;
}

/* ------------------------------------------------------------------ */

static void test_util(void)
{
    char out[64];
    sbuf b;
    char s[40];

    CHECK(b64_encode((const unsigned char *)"", 0, out, sizeof out) == 0);
    CHECK(b64_encode((const unsigned char *)"f", 1, out, sizeof out) == 4);
    CHECK_STR(out, "Zg==");
    b64_encode((const unsigned char *)"fo", 2, out, sizeof out);
    CHECK_STR(out, "Zm8=");
    b64_encode((const unsigned char *)"foo", 3, out, sizeof out);
    CHECK_STR(out, "Zm9v");
    b64_encode((const unsigned char *)"pi-star:raspberry", 17, out, sizeof out);
    CHECK_STR(out, "cGktc3RhcjpyYXNwYmVycnk=");
    CHECK(b64_encode((const unsigned char *)"foobar", 6, out, 8) == 0);

    url_encode("Add & Link", out, sizeof out);
    CHECK_STR(out, "Add+%26+Link");
    url_encode("a-b_c.d~e", out, sizeof out);
    CHECK_STR(out, "a-b_c.d~e");
    url_encode("91,\n92", out, sizeof out);
    CHECK_STR(out, "91%2C%0A92");
    CHECK(url_encode("0123456789", out, 5) == (size_t)-1);
    CHECK(url_encode("%%%", out, 6) == (size_t)-1);

    CHECK(u_ieq("DMR", "dmr"));
    CHECK(!u_ieq("DMR", "dmrx"));
    CHECK(u_istarts("Content-Length: 5", "content-length:"));
    CHECK(u_find("hello world", 11, "o w") != NULL);
    CHECK(u_find("hello", 3, "llo") == NULL);       /* respects the length */
    CHECK(u_ifind("Hello", 5, "ELL") != NULL);

    strcpy(s, "  \t x y \r\n");
    u_trim(s);
    CHECK_STR(s, "x y");

    CHECK(u_copy(s, 4, "abcdef") == 3);
    CHECK_STR(s, "abc");

    sb_init(&b, 10);
    CHECK(sb_add(&b, "12345", 5) == 0);
    CHECK(sb_add(&b, "6789012345", 10) == 1);      /* truncated at 10 */
    CHECK(b.len == 10);
    CHECK(b.truncated);
    CHECK_STR(sb_str(&b), "1234567890");
    sb_free(&b);
    CHECK_STR(sb_str(&b), "");

    strcpy(s, "caf\xC3\xA9 \xE2\x80\x93 \xE2\x82\xAC \xF0\x9F\x98\x80 ok");
    utf8_to_latin1(s);
    CHECK_STR(s, "caf\xE9 - E ? ok");

    strcpy(s, "already \xE9 latin1");     /* lone 0xE9 stays */
    utf8_to_latin1(s);
    CHECK_STR(s, "already \xE9 latin1");

    strcpy(s, "trunc \xE2\x82");           /* cut mid-sequence */
    utf8_to_latin1(s);
    CHECK(strncmp(s, "trunc ", 6) == 0);
}

static void test_display_text(void)
{
    char t[80];

    /* New lines, tabs and other control characters become one space: the
     * desktop ends text at the first byte below 32. */
    u_copy(t, sizeof t, "Stopping\nStarting\t\tWPSD\r\nservices");
    utf8_to_latin1(t);
    CHECK_STR(t, "Stopping Starting WPSD services");

    u_copy(t, sizeof t, "a\001b\177c");
    utf8_to_latin1(t);
    CHECK_STR(t, "a b c");

    /* Colour codes are dropped, not shown as junk. */
    u_copy(t, sizeof t, "\033[32mdone\033[0m");
    utf8_to_latin1(t);
    CHECK_STR(t, "done");
    u_copy(t, sizeof t, "x\033[1;31;40my\033");     /* a lone ESC is a control character */
    utf8_to_latin1(t);
    CHECK_STR(t, "xy ");
    u_copy(t, sizeof t, "unterminated \033[12");
    utf8_to_latin1(t);
    CHECK_STR(t, "unterminated ");

    /* UTF-8 still comes out as Latin-1. */
    u_copy(t, sizeof t, "\xC2\xA9 Acorn \xE2\x80\x94 ok");
    utf8_to_latin1(t);
    CHECK_STR(t, "\xA9 Acorn - ok");

    u_copy(t, sizeof t, "line one\ntwo\x01\x1f three\x7f");
    u_no_ctrl(t);
    CHECK_STR(t, "line one two   three ");
}

static void test_scan_prefix(void)
{
    char out[24];

    CHECK(scan_prefix_from("10.0.0.27", out, sizeof out) && strcmp(out, "10.0.0.") == 0);
    CHECK(scan_prefix_from("10.0.0", out, sizeof out) && strcmp(out, "10.0.0.") == 0);
    CHECK(scan_prefix_from("10.0.0.", out, sizeof out) && strcmp(out, "10.0.0.") == 0);
    CHECK(scan_prefix_from("  192.168.1.254  ", out, sizeof out) &&
          strcmp(out, "192.168.1.") == 0);
    CHECK(scan_prefix_from("127.0.0.1\n", out, sizeof out) && strcmp(out, "127.0.0.") == 0);
    CHECK(!scan_prefix_from("", out, sizeof out));
    CHECK(!scan_prefix_from("10.0", out, sizeof out));
    CHECK(!scan_prefix_from("10", out, sizeof out));
    CHECK(!scan_prefix_from("10.0.0.1.5", out, sizeof out));
    CHECK(!scan_prefix_from("10.0.256.1", out, sizeof out));
    CHECK(!scan_prefix_from("10.0..1", out, sizeof out));
    CHECK(!scan_prefix_from("wpsd.local", out, sizeof out));
    CHECK(!scan_prefix_from("10.0.0.1x", out, sizeof out));
    CHECK(!scan_prefix_from("1000.0.0.1", out, sizeof out));
    CHECK(scan_new("nonsense", 80) == NULL);
}

static void test_html(void)
{
    char out[128];
    const char *h;
    const char *te;
    const char *d;
    const char *close;
    int v;

    h = "<span>M1ABC&nbsp B</span>";
    html_text(h, strlen(h), out, sizeof out);
    CHECK_STR(out, "M1ABC B");

    h = "<p>a  &amp;  b &lt;c&gt; &#39;q&#x27; &deg;C&nbsp;&bull;x</p>";
    html_text(h, strlen(h), out, sizeof out);
    CHECK_STR(out, "a & b <c> 'q' \xB0" "C *x");

    h = "x<!-- hidden <b>stuff</b> -->y<script>var a='<b>';</script>z"
        "<style>.a{}</style>w";
    html_text(h, strlen(h), out, sizeof out);
    CHECK_STR(out, "xyzw");

    h = "a<br />b</div>c&unknown;d & e";
    html_text(h, strlen(h), out, sizeof out);
    CHECK_STR(out, "a b c&unknown;d & e");

    html_text("abcdefghij", 10, out, 5);
    CHECK_STR(out, "abcd");

    /* Line-structured text keeps block boundaries as newlines. */
    h = "<div class=\"a\"> Mode  Status </div><div><span>DMR</span> <span>on</span></div>"
        "<br />third<p>fourth&nbsp;line</p>\n\n<div></div><div>last</div>";
    html_lines(h, strlen(h), out, sizeof out);
    CHECK_STR(out, "Mode Status\nDMR on\nthird\nfourth line\nlast");
    html_lines("</div></div>  x", 15, out, sizeof out);
    CHECK_STR(out, "x");
    html_lines("<td>a</td><td>b</td>", 20, out, sizeof out);
    CHECK_STR(out, "a b");

    /* Nested divs: the matching close, not the first one. */
    h = "<div id=a>x<div>y</div><div>z<div>w</div></div>t</div>after";
    d = html_find_tag(h, h + strlen(h), "div", &te);
    CHECK(d == h);
    close = html_div_close(te, h + strlen(h));
    CHECK(close != NULL && strncmp(close, "</div>after", 11) == 0);

    h = "<div class='x'><div class=\"status-pill active\" data-n=\"42\">t</div></div>";
    d = html_find_div(h, h + strlen(h), "status-pill", &te);
    CHECK(d != NULL);
    CHECK(html_attr_int(d, te, "data-n", &v) && v == 42);
    CHECK(!html_attr_int(d, te, "data-q", &v));
    {
        char val[16];

        CHECK(html_attr_str(d, te, "data-n", val, sizeof val) && strcmp(val, "42") == 0);
        CHECK(!html_attr_str(d, te, "data-q", val, sizeof val));
        CHECK(!html_attr_str(d, te, "data-n", val, 2));       /* did not fit */
    }

    /* Truncated input must not run off the end. */
    h = "<div class=\"abc";
    CHECK(html_find_tag(h, h + strlen(h), "div", &te) == NULL);
    CHECK(html_div_close(h, h + strlen(h)) == NULL);
}

static void test_json(void)
{
    const char *t1 = "[{\"a\":\"x\\/y\",\"b\":\"caf\\u00e9\",\"n\":12,\"t\":true,"
                     "\"z\":null,\"o\":{\"k\":[1,2,3]}}, {\"a\":\"\"}]";
    jnode *r = json_parse(t1, strlen(t1));
    const jnode *o;
    char tmp[16];

    CHECK(r != NULL && r->t == J_ARR && json_count(r) == 2);
    o = json_at(r, 0);
    CHECK_STR(json_string(o, "a", "?"), "x/y");
    u_copy(tmp, sizeof tmp, json_string(o, "b", "?"));
    utf8_to_latin1(tmp);
    CHECK_STR(tmp, "caf\xE9");
    CHECK(json_int(o, "n", -1) == 12);
    CHECK(json_int(o, "t", -1) == 1);
    CHECK(json_int(o, "missing", 7) == 7);
    CHECK_STR(json_string(o, "n", "dflt"), "dflt");     /* not a string */
    CHECK(json_count(json_member(json_member(o, "o"), "k")) == 3);
    CHECK_STR(json_string(json_at(r, 1), "a", "?"), "");
    json_free(r);

    /* Surrogate pair. */
    r = json_parse("\"\\ud83d\\ude00\"", 14);
    CHECK(r != NULL && r->t == J_STR && strlen(r->s) == 4);
    json_free(r);

    /* Errors. */
    CHECK(json_parse("[1,2", 4) == NULL);
    CHECK(json_parse("{\"a\":}", 6) == NULL);
    CHECK(json_parse("[1] x", 5) == NULL);
    CHECK(json_parse("", 0) == NULL);
    CHECK(json_parse("\"abc", 4) == NULL);
    CHECK(json_parse("\"a\\q\"", 5) == NULL);

    {
        char deep[200];
        int i;

        for (i = 0; i < 100; i++)
            deep[i] = '[';
        for (i = 0; i < 100; i++)
            deep[100 + i] = ']';
        CHECK(json_parse(deep, 200) == NULL);      /* nesting limit */
    }
}

/* ------------------------------------------------------------------ */

static int find_pill(const wpsd_status *st, const char *label, int nth)
{
    int i;

    for (i = 0; i < st->npill; i++) {
        if (strcmp(st->pill[i].label, label) == 0 && nth-- == 0)
            return i;
    }

    return -1;
}

static void test_status(void)
{
    size_t n;
    char *h = load("repeaterinfo_basic.html", &n);
    wpsd_status *st = (wpsd_status *)malloc(sizeof *st);
    int i;

    CHECK(wpsd_parse_status(h, n, st) == 30);
    CHECK(st->nsec == 9);
    CHECK_STR(st->sec[0].title, "Modes Enabled");
    CHECK_STR(st->sec[1].title, "Network Status");
    CHECK_STR(st->sec[2].title, "D-Star Status");
    CHECK_STR(st->sec[3].title, "D-Star Network");
    CHECK_STR(st->sec[4].title, "DMR Status");
    CHECK_STR(st->sec[5].title, "DMR Master");
    CHECK_STR(st->sec[6].title, "YSF Status [Linked]");

    i = find_pill(st, "DMR", 0);
    CHECK(i == 1 && st->pill[i].state == PILL_ACTIVE && st->pill[i].section == 0);
    i = find_pill(st, "P25", 0);
    CHECK(i >= 0 && st->pill[i].state == PILL_INACTIVE);

    i = find_pill(st, "RPT1", 0);
    CHECK(i >= 0);
    CHECK_STR(st->pill[i].value, "M1ABC B");

    i = find_pill(st, "Link", 0);
    CHECK(i >= 0);
    CHECK_STR(st->pill[i].value, "REF001 C");
    CHECK(st->pill[i].section == 3);

    /* The second "Link" is the YSF one, inside pill-data. */
    i = find_pill(st, "Link", 1);
    CHECK(i >= 0);
    CHECK_STR(st->pill[i].value, "UK-Calling");

    /* A pill with only a label and an icon. */
    i = find_pill(st, "BM 2341 United Kingdom", 0);
    CHECK(i >= 0 && st->pill[i].state == PILL_ACTIVE);
    CHECK(st->pill[i].value[0] == '\0');
    CHECK_STR(st->sec[st->pill[i].section].title, "DMR Master");

    /* The stray quote the PHP helper leaves behind must not hide the state. */
    i = find_pill(st, "Public", 0);
    CHECK(i >= 0 && st->pill[i].state == PILL_ACTIVE);
    CHECK_STR(st->pill[i].value, "On");

    /* A text-only pill (a link, no spans). */
    i = find_pill(st, "No more modes", 0);
    CHECK(i >= 0 && st->pill[i].state == PILL_INACTIVE);

    /* The APRS section repeats mode names but is not the first section. */
    i = find_pill(st, "DMR", 1);
    CHECK(i >= 0 && st->pill[i].section == 8);

    free(h);

    h = load("repeaterinfo_dmr_paused.html", &n);
    CHECK(wpsd_parse_status(h, n, st) > 0);
    i = find_pill(st, "DMR", 0);
    CHECK(st->pill[i].state == PILL_PAUSED);
    i = find_pill(st, "Mode Paused", 0);
    CHECK(i >= 0);
    free(h);

    h = load("repeaterinfo_allmodes.html", &n);
    CHECK(wpsd_parse_status(h, n, st) > 30);
    i = find_pill(st, "NAC", 0);
    CHECK(i >= 0);
    CHECK_STR(st->pill[i].value, "293");
    i = find_pill(st, "RAN", 0);
    CHECK(i >= 0);
    free(h);

    /* Garbage in, nothing out. */
    CHECK(wpsd_parse_status("<html>nothing here</html>", 25, st) == 0);
    CHECK(wpsd_parse_status("", 0, st) == 0);

    /* Truncated mid-pill must not crash or loop. */
    h = load("repeaterinfo_basic.html", &n);
    for (i = 1; i < 400; i += 7)
        wpsd_parse_status(h, (size_t)i, st);
    free(h);

    free(st);
}

static void test_radio_hw(void)
{
    size_t n;
    char *h = load("radioinfo_idle.html", &n);
    wpsd_radio r;
    wpsd_hw *hw = (wpsd_hw *)malloc(sizeof *hw);
    int i;

    CHECK(wpsd_parse_radio(h, n, &r) == 1);
    CHECK_STR(r.state, "IDLE");
    CHECK(r.n == 7);
    CHECK_STR(r.kv[0].key, "Radio Status");
    CHECK_STR(r.kv[1].key, "TX/RX Freq.");
    CHECK_STR(r.kv[1].val, "438.800 MHz");
    CHECK_STR(r.kv[6].key, "Modem Type");
    free(h);

    h = load("radioinfo_tx.html", &n);
    CHECK(wpsd_parse_radio(h, n, &r) == 1);
    CHECK_STR(r.state, "TX: DMR");
    free(h);
    h = load("radioinfo_rx.html", &n);
    CHECK(wpsd_parse_radio(h, n, &r) == 1);
    CHECK_STR(r.state, "RX: DMR");
    free(h);
    h = load("radioinfo_offline.html", &n);
    CHECK(wpsd_parse_radio(h, n, &r) == 1);
    CHECK_STR(r.state, "OFFLINE");
    free(h);

    CHECK(wpsd_parse_radio("<p>hi</p>", 9, &r) == 0);

    h = load("hwinfo.html", &n);
    CHECK(wpsd_parse_hw(h, n, hw) == 1);
    CHECK(hw->n == 10);
    CHECK_STR(hw->kv[0].key, "CPU Load");
    CHECK_STR(hw->kv[0].val, "12%");
    CHECK_STR(hw->kv[1].key, "Hardware");
    CHECK_STR(hw->kv[1].val, "Raspberry Pi Zero 2 W Rev 1.0");
    CHECK_STR(hw->kv[3].key, "OS");
    for (i = 0; i < hw->n; i++) {
        if (strcmp(hw->kv[i].key, "CPU Temp") == 0)
            CHECK_STR(hw->kv[i].val, "130\xB0" "F / 54\xB0" "C");
        if (strcmp(hw->kv[i].key, "Uptime") == 0)
            CHECK_STR(hw->kv[i].val, "3 days, 4 hours, 12 minutes");
    }
    free(h);
    free(hw);
}

static void test_heard(void)
{
    size_t n;
    char *j = load("api_lastheard.json", &n);
    wpsd_lastheard *lh = (wpsd_lastheard *)malloc(sizeof *lh);

    CHECK(wpsd_parse_heard(j, n, lh) == 1);
    CHECK(lh->n == 8);
    CHECK_STR(lh->row[0].time, "07:12:11");
    CHECK_STR(lh->row[0].mode, "DMR Slot 2");
    CHECK_STR(lh->row[0].call, "G4ABC");
    CHECK_STR(lh->row[0].target, "TG 91");
    CHECK_STR(lh->row[0].src, "Net");
    CHECK_STR(lh->row[0].dur, "4.2");
    CHECK_STR(lh->row[0].loss, "0%");
    CHECK(!lh->row[0].active);
    CHECK_STR(lh->row[1].mode, "D-Star");
    CHECK_STR(lh->row[1].src, "RF");
    free(j);

    j = load("api_lastheard_names.json", &n);
    CHECK(wpsd_parse_heard(j, n, lh) == 1);
    CHECK_STR(lh->row[0].name, "Alice");
    CHECK_STR(lh->row[0].country, "England");
    free(j);

    j = load("api_lastheard_rx.json", &n);
    CHECK(wpsd_parse_heard(j, n, lh) == 1);
    CHECK(lh->row[0].active);
    CHECK(!lh->row[1].active);
    free(j);

    /* PHP warnings printed in front of (or after) the JSON are skipped. */
    {
        const char *noisy =
            "<br />\n<b>Warning</b>:  Undefined variable $x in <b>/var/www/a.php</b> "
            "on line 3<br />\n[{\"time_utc\":\"2026-10-04 07:00:01\",\"mode\":\"DMR\","
            "\"callsign\":\"G4ABC\",\"target\":\"TG 91\",\"src\":\"Net\","
            "\"duration\":\"1.0\",\"loss\":\"0%\"}]\n<!-- trailing -->";

        CHECK(wpsd_parse_heard(noisy, strlen(noisy), lh) == 1 && lh->n == 1);
        CHECK_STR(lh->row[0].call, "G4ABC");
    }

    CHECK(wpsd_parse_heard("[]", 2, lh) == 1 && lh->n == 0);
    CHECK(wpsd_parse_heard("{\"a\":1}", 7, lh) == 0);
    CHECK(wpsd_parse_heard("<html>", 6, lh) == 0);
    CHECK(wpsd_parse_heard("[{\"time_utc\":", 13, lh) == 0);
    free(lh);
}

static void test_bm(void)
{
    size_t n;
    char *h = load("bm_page.html", &n);
    wpsd_bm *bm = (wpsd_bm *)malloc(sizeof *bm);

    CHECK(wpsd_parse_bm(h, n, bm) == 1);
    CHECK(bm->ok);
    CHECK_STR(bm->id, "2345678");
    CHECK_STR(bm->network, "BM_2341_United_Kingdom");
    CHECK(bm->nst == 3);
    CHECK(bm->st[0].tg == 91 && bm->st[0].slot == 0 && bm->st[0].disp_slot == 2);
    CHECK(bm->st[0].linked);
    CHECK_STR(bm->st[0].name, "Worldwide");
    CHECK(bm->st[1].tg == 235 && bm->st[1].linked);
    CHECK(bm->st[2].tg == 9990 && !bm->st[2].linked);
    CHECK(bm->ndyn == 1);
    CHECK(bm->dyn[0].tg == 2341);
    CHECK_STR(bm->dyn[0].name, "UK Calling");
    CHECK_STR(bm->dyn[0].timeout, "07:25:11 (3:21)");
    CHECK(bm->ndrop == 1 && bm->drop_slot[0] == 0);
    free(h);

    h = load("bm_page_duplex.html", &n);
    CHECK(wpsd_parse_bm(h, n, bm) == 1);
    CHECK(bm->ndrop == 2 && bm->drop_slot[0] == 1 && bm->drop_slot[1] == 2);
    free(h);

    h = load("bm_notice.html", &n);
    CHECK(wpsd_parse_bm(h, n, bm) == 1);
    CHECK(!bm->ok);
    CHECK(strstr(bm->notice, "No BrandMeister API key") != NULL);
    free(h);

    /* A page that is not the BM manager at all. */
    CHECK(wpsd_parse_bm("<html><body>Nope</body></html>", 30, bm) == 0);
    CHECK(wpsd_parse_bm("", 0, bm) == 0);

    h = load("bm_page.html", &n);
    {
        size_t i;

        for (i = 1; i < n; i += 97)
            wpsd_parse_bm(h, i, bm);
    }
    free(h);
    free(bm);
}

static void test_tgif_and_networks(void)
{
    size_t n;
    char *t;
    wpsd_tgif tg;
    wpsd_dmrnets nets;
    wpsd_status *st = (wpsd_status *)malloc(sizeof *st);
    wpsd_result r;
    int i;

    t = load("tgif_links.html", &n);
    CHECK(wpsd_parse_tgif(t, n, &tg) == 1);
    CHECK(tg.ok);
    CHECK_STR(tg.id, "2345678");
    CHECK(tg.tg[0] == 0 && tg.tg[1] == 91);
    CHECK_STR(tg.name[0], "");
    CHECK_STR(tg.name[1], "Worldwide");
    free(t);

    t = load("tgif_links_none.html", &n);
    CHECK(wpsd_parse_tgif(t, n, &tg) == 1);
    CHECK(tg.tg[0] == 0 && tg.tg[1] == 0);
    free(t);

    t = load("tgif_links_unused.html", &n);          /* TGIF not configured */
    CHECK(wpsd_parse_tgif(t, n, &tg) == 0);
    CHECK(!tg.ok);
    free(t);
    CHECK(wpsd_parse_tgif("<b>Active TGIF Connections</b><table><tr><td>x", 47, &tg) == 0);

    t = load("dmr_nets.html", &n);
    CHECK(wpsd_parse_dmrnets(t, n, &nets) == 1);
    CHECK(nets.n == 2);
    CHECK_STR(nets.net[0].id, "net1");
    CHECK_STR(nets.net[0].name, "BM 2341 United Kingdom");
    CHECK(nets.net[0].enabled);
    CHECK_STR(nets.net[1].id, "net4");
    CHECK_STR(nets.net[1].name, "TGIF Network");
    CHECK(nets.net[1].enabled);
    free(t);

    t = load("dmr_nets_tgif_off.html", &n);
    CHECK(wpsd_parse_dmrnets(t, n, &nets) == 1);
    CHECK(nets.net[0].enabled && !nets.net[1].enabled);
    free(t);

    /* The page only lists networks when there are two or more. */
    t = load("dmr_nets_single.html", &n);
    CHECK(wpsd_parse_dmrnets(t, n, &nets) == 0);
    free(t);

    /* A gateway hotspot shows each network as its own pill; a disabled one
     * is "paused". */
    t = load("repeaterinfo_gateway_tgif_off.html", &n);
    CHECK(wpsd_parse_status(t, n, st) > 0);
    CHECK_STR(st->sec[5].title, "DMR Masters");
    for (i = 0; i < st->npill; i++) {
        if (strcmp(st->pill[i].label, "TGIF Network") == 0)
            CHECK(st->pill[i].state == PILL_PAUSED);
        if (strcmp(st->pill[i].label, "BM 2341 United Kingdom") == 0)
            CHECK(st->pill[i].state == PILL_ACTIVE);
    }
    free(t);
    free(st);

    t = load("api_result_dmrnet_ok.json", &n);
    CHECK(wpsd_parse_api_result(t, n, &r) == 1 && r.ok);
    CHECK_STR(r.msg, "OK");
    free(t);
    t = load("api_result_dmrnet_ko.json", &n);
    CHECK(wpsd_parse_api_result(t, n, &r) == 1 && !r.ok);
    free(t);
    {
        const char *multi = "{\"commandOutput\":\"Sending...\\nOK\"}";
        const char *word = "{\"commandOutput\":\"KOALA done\"}";

        CHECK(wpsd_parse_api_result(multi, strlen(multi), &r) == 1 && r.ok);
        CHECK_STR(r.msg, "OK");
        CHECK(wpsd_parse_api_result(word, strlen(word), &r) == 1 && r.ok);
    }
}

static void test_results(void)
{
    size_t n;
    char *t;
    wpsd_result r;

    t = load("api_result_restart.json", &n);
    CHECK(wpsd_parse_api_result(t, n, &r) == 1);
    CHECK(r.ok);
    CHECK_STR(r.msg, "Starting WPSD services...done");
    free(t);

    t = load("api_result_error.json", &n);
    CHECK(wpsd_parse_api_result(t, n, &r) == 1);
    CHECK(!r.ok);
    CHECK_STR(r.msg, "tg and slot params required");
    free(t);

    t = load("api_result_success.json", &n);
    CHECK(wpsd_parse_api_result(t, n, &r) == 1 && r.ok);
    CHECK_STR(r.msg, "done");
    free(t);

    t = load("api_result_ip.json", &n);
    CHECK(wpsd_parse_api_result(t, n, &r) == 1 && r.ok);
    CHECK_STR(r.msg, "IP address 10.0.0.50");
    free(t);

    {
        const char *failed = "{\"output\":[],\"exit_status\":3}";

        CHECK(wpsd_parse_api_result(failed, strlen(failed), &r) == 1);
    }
    CHECK(!r.ok);
    CHECK_STR(r.msg, "failed (exit status 3)");
    CHECK(wpsd_parse_api_result("<html>login</html>", 18, &r) == 0);
    CHECK(!r.ok);

    {
        const char *noisy = "\nWarning: Undefined array key \"cmd\" in x.php on "
                            "line 9\n{\"success\":true}\n";

        CHECK(wpsd_parse_api_result(noisy, strlen(noisy), &r) == 1 && r.ok);
    }

    t = load("mode_reply_paused.html", &n);
    CHECK(wpsd_parse_manager_reply(t, n, "imm", &r) == 1);
    CHECK(r.ok);
    CHECK_STR(r.msg, "Paused: DMR Services are stopping...");
    CHECK(wpsd_parse_manager_reply(t, n, "ysf", &r) == 0);
    free(t);

    t = load("mode_reply_already.html", &n);
    CHECK(wpsd_parse_manager_reply(t, n, "imm", &r) == 1);
    CHECK(!r.ok);
    CHECK_STR(r.msg, "DMR is already paused.");
    free(t);

    t = load("ysf_reply_ok.html", &n);
    CHECK(wpsd_parse_manager_reply(t, n, "ysf", &r) == 1 && r.ok);
    CHECK_STR(r.msg, "Command Sent Linked to YSF00001");
    free(t);

    t = load("ysf_reply_error.html", &n);
    CHECK(wpsd_parse_manager_reply(t, n, "ysf", &r) == 1 && !r.ok);
    CHECK_STR(r.msg, "Error: No target specified. Please try again.");
    free(t);

    t = load("dstar_reply_ok.html", &n);
    CHECK(wpsd_parse_manager_reply(t, n, "dstar", &r) == 1 && r.ok);
    free(t);
}

static void test_builders(void)
{
    wpsd_request rq;

    CHECK(wpsd_req_heard(&rq, 15, 0) == 0);
    CHECK_STR(rq.target, "/api/?limit=15&names=false&country=false");
    CHECK(strcmp(rq.method, "GET") == 0 && !rq.auth);
    wpsd_req_heard(&rq, 999, 1);
    CHECK_STR(rq.target, "/api/?limit=50&names=true&country=false");

    wpsd_req_radio(&rq);
    CHECK_STR(rq.target, "/mmdvmhost/radioinfo.php");
    wpsd_req_status(&rq);
    CHECK_STR(rq.target, "/mmdvmhost/repeaterinfo.php");
    wpsd_req_hw(&rq);
    CHECK_STR(rq.target, "/includes/hw_info.php");
    wpsd_req_bm_page(&rq);
    CHECK_STR(rq.target, "/admin/bm-manager.php");
    CHECK(rq.auth);

    CHECK(wpsd_req_mode(&rq, "DMR", 1) == 0);
    CHECK(strcmp(rq.method, "POST") == 0 && rq.auth);
    CHECK_STR(rq.target, "/admin/index.php?func=mode_man");
    CHECK_STR(rq.body, "mode_action=Pause&mode_sel=DMR&func=mode_man&"
                       "submit_mode=Execute+Action");
    CHECK_STR(rq.reply_prefix, "imm");
    wpsd_req_mode(&rq, "D-Star", 0);
    CHECK_STR(rq.body, "mode_action=Resume&mode_sel=D-Star&func=mode_man&"
                       "submit_mode=Execute+Action");
    CHECK(wpsd_req_mode(&rq, "DMR;rm", 1) < 0);
    CHECK(wpsd_req_mode(&rq, "", 1) < 0);

    CHECK(wpsd_req_sysapi(&rq, "restart_wpsd_services") == 0);
    CHECK_STR(rq.target,
              "/admin/system_api.php?action=restart_wpsd_services&format=json");
    CHECK(rq.json_reply);
    CHECK(wpsd_req_sysapi(&rq, "a&b=c") < 0);
    CHECK(wpsd_req_sysapi(&rq, "") < 0);

    CHECK(wpsd_req_bm_link(&rq, 91, 0, 1) == 0);
    CHECK_STR(rq.target, "/admin/system_api.php?action=bm_manager&"
                         "cmd=link_static&tg=91&slot=0&format=json");
    wpsd_req_bm_link(&rq, 91, 2, 0);
    CHECK(strstr(rq.target, "cmd=drop_static&tg=91&slot=2") != NULL);
    CHECK(wpsd_req_bm_link(&rq, 0, 0, 1) < 0);
    CHECK(wpsd_req_bm_link(&rq, 91, 3, 1) < 0);
    wpsd_req_bm_drop_dynamic(&rq, 1);
    CHECK(strstr(rq.target, "cmd=drop_dynamic&slot=1") != NULL);
    wpsd_req_bm_drop_qso(&rq, 2);
    CHECK(strstr(rq.target, "cmd=drop_qso&slot=2") != NULL);

    CHECK(wpsd_req_bm_add(&rq, "91, 92", 0) == 0);
    CHECK_STR(rq.target, "/admin/bm-manager.php");
    CHECK_STR(rq.body, "TG=91%2C+92&TS=0&static-tg-add=Add+%26+Link");
    CHECK(wpsd_req_bm_add(&rq, "91;rm -rf", 0) < 0);
    CHECK(wpsd_req_bm_add(&rq, "abc", 0) < 0);
    CHECK(wpsd_req_bm_add(&rq, "", 0) < 0);

    CHECK(wpsd_req_bm_delete(&rq, 91, 0) == 0);
    CHECK_STR(rq.target, "/admin/bm-manager.php?droptg=91&slot=0");

    CHECK(wpsd_req_ysf(&rq, "00001", 1) == 0);
    CHECK_STR(rq.target, "/admin/index.php?func=ysf_man");
    CHECK_STR(rq.body, "ysfLinkHost=YSF00001&Link=LINK&func=ysf_man&"
                       "ysfMgrSubmit=Execute+Action");
    wpsd_req_ysf(&rq, "fcs00123", 1);
    CHECK(strstr(rq.body, "ysfLinkHost=FCS00123&Link=LINK") != NULL);
    wpsd_req_ysf(&rq, NULL, 0);
    CHECK(strstr(rq.body, "ysfLinkHost=none&Link=UNLINK") != NULL);
    wpsd_req_ysf(&rq, "none", 1);
    CHECK(strstr(rq.body, "ysfLinkHost=none&Link=LINK") != NULL);
    CHECK(wpsd_req_ysf(&rq, "bad host", 1) < 0);
    CHECK(wpsd_req_ysf(&rq, "", 1) < 0);

    CHECK(wpsd_req_p25(&rq, "10100", 1) == 0);
    CHECK_STR(rq.body, "p25LinkHost=10100&Link=LINK&func=p25_man&"
                       "p25MgrSubmit=Execute+Action");
    wpsd_req_p25(&rq, "10100", 0);
    CHECK(strstr(rq.body, "p25LinkHost=none&Link=UNLINK") != NULL);
    CHECK(wpsd_req_nxdn(&rq, "20", 1) == 0);
    CHECK_STR(rq.body, "nxdnLinkHost=20&Link=LINK&func=nxdn_man&"
                       "nxdnMgrSubmit=Execute+Action");
    CHECK(wpsd_req_nxdn(&rq, "2 0", 1) < 0);

    CHECK(wpsd_req_dstar(&rq, "M1ABC  B", "ref001", "c", 1) == 0);
    CHECK_STR(rq.target, "/admin/index.php?func=ds_man");
    CHECK_STR(rq.body, "Module=M1ABC++B&RefName=REF001&Letter=C&Link=LINK&"
                       "func=ds_man&dstrMgrSubmit=Execute+Action");
    /* Unlinking must still send a reflector/letter or the dashboard
     * answers "Invalid Input". */
    CHECK(wpsd_req_dstar(&rq, "M1ABC B", NULL, NULL, 0) == 0);
    CHECK(strstr(rq.body, "Module=M1ABC+B&RefName=REF001&Letter=A&Link=UNLINK")
          != NULL);
    CHECK(wpsd_req_dstar(&rq, "M1ABC B", "REF 001", "C", 1) < 0);
    CHECK(wpsd_req_dstar(&rq, "M1;ABC", "REF001", "C", 1) < 0);
    CHECK(wpsd_req_dstar(&rq, "M1ABC B", "REF001", "CC", 1) < 0);

    CHECK(wpsd_req_tgif(&rq, 91, 2, 1) == 0);
    CHECK_STR(rq.body, "tgifAction=LINK&tgifNumber=91&tgifSlot=2&func=tgif_man&"
                       "tgifSubmit=Execute+Action");
    CHECK(wpsd_req_tgif(&rq, 0, 2, 1) < 0);
    wpsd_req_tgif(&rq, 0, 2, 0);
    CHECK_STR(rq.body, "tgifAction=UNLINK&tgifNumber=0&tgifSlot=2&func=tgif_man&"
                       "tgifSubmit=Execute+Action");

    CHECK(wpsd_req_tgif_links(&rq) == 0);
    CHECK_STR(rq.target, "/mmdvmhost/tgif_links.php");
    CHECK(!rq.auth);
    CHECK(wpsd_req_dmrnets(&rq) == 0);
    CHECK_STR(rq.target, "/admin/index.php?func=dmr_man");
    CHECK(rq.auth && strcmp(rq.method, "GET") == 0);

    CHECK(wpsd_req_dmrnet_set(&rq, "net4", 0) == 0);
    CHECK_STR(rq.target, "/admin/system_api.php?action=dmrnet_set_status&"
                         "dmrNet=net4&netState=disable&format=json");
    CHECK(rq.json_reply);
    wpsd_req_dmrnet_set(&rq, "xlx", 1);
    CHECK(strstr(rq.target, "dmrNet=xlx&netState=enable") != NULL);
    CHECK(wpsd_req_dmrnet_set(&rq, "net", 1) < 0);
    CHECK(wpsd_req_dmrnet_set(&rq, "net4;rm", 1) < 0);
    CHECK(wpsd_req_dmrnet_set(&rq, "network", 1) < 0);
    CHECK(wpsd_req_dmrnet_set(&rq, NULL, 1) < 0);
}

/* ------------------------------------------------------------------ */

static int count_buttons(const ui_rows *r, int action, const char *arg)
{
    int i;
    int j;
    int n = 0;

    for (i = 0; i < r->n; i++) {
        for (j = 0; j < r->row[i].nbtn; j++) {
            if (r->row[i].btn[j].action == action &&
                (arg == NULL || strcmp(r->row[i].btn[j].arg, arg) == 0))
                n++;
        }
    }

    return n;
}

static const ui_btn *find_button(const ui_rows *r, int action, const char *arg)
{
    int i;
    int j;

    for (i = 0; i < r->n; i++) {
        for (j = 0; j < r->row[i].nbtn; j++) {
            if (r->row[i].btn[j].action == action &&
                (arg == NULL || strcmp(r->row[i].btn[j].arg, arg) == 0))
                return &r->row[i].btn[j];
        }
    }

    return NULL;
}

static void load_model(hs_model *m, const char *status_file,
                       const char *radio_file)
{
    size_t n;
    char *t;

    memset(m, 0, sizeof *m);
    m->conn = 1;

    t = load(status_file, &n);
    m->status_ok = wpsd_parse_status(t, n, &m->status) > 0;
    free(t);

    t = load(radio_file, &n);
    m->radio_ok = wpsd_parse_radio(t, n, &m->radio);
    free(t);

    t = load("hwinfo.html", &n);
    m->hw_ok = wpsd_parse_hw(t, n, &m->hw);
    free(t);

    t = load("api_lastheard_rx.json", &n);
    m->heard_ok = wpsd_parse_heard(t, n, &m->heard);
    free(t);

    t = load("bm_page.html", &n);
    m->bm_state = wpsd_parse_bm(t, n, &m->bm) ? 1 : -1;
    free(t);
}

static void test_rows(void)
{
    hs_model *m = (hs_model *)malloc(sizeof *m);
    hs_config cfg;
    ui_rows r;
    const ui_btn *b;
    int v;

    ui_rows_init(&r);
    hs_config_defaults(&cfg);
    u_copy(cfg.host, sizeof cfg.host, "10.0.0.50");

    load_model(m, "repeaterinfo_basic.html", "radioinfo_rx.html");
    ui_rows_build(&r, m, &cfg, VIEW_STATUS);
    CHECK(r.n > 20);
    CHECK(r.row[0].kind == UR_HEAD);
    CHECK_STR(r.row[0].col[0], "Hotspot  10.0.0.50");
    CHECK(r.row[0].nbtn == 3);
    CHECK(r.row[0].btn[0].action == UA_REFRESH);
    CHECK(r.row[0].btn[1].action == UA_FIND);
    CHECK(r.row[0].btn[2].action == UA_CHOICES);
    CHECK(r.row[1].kind == UR_NOTE && r.row[1].style == US_GOOD);
    CHECK(r.row[2].kind == UR_TABS && r.row[2].nbtn == VIEW_COUNT);
    CHECK(r.row[2].selected == VIEW_STATUS);

    /* Pause on the three active modes - and only those: the APRS section
     * repeats mode names and must not get buttons. */
    CHECK(count_buttons(&r, UA_MODE, NULL) == 3);
    b = find_button(&r, UA_MODE, "DMR");
    CHECK(b != NULL && strcmp(b->label, "Pause") == 0 && b->a[0] == 1);
    CHECK(find_button(&r, UA_MODE, "P25") == NULL);

    ui_rows_build(&r, m, &cfg, VIEW_HEARD);
    CHECK(r.row[r.n - 1].kind == UR_HEARD);
    for (v = 0; v < r.n; v++) {
        if (r.row[v].kind == UR_HEARD && r.row[v].style == US_ACTIVE)
            break;
    }
    CHECK(v < r.n);        /* the live transmission is highlighted */

    ui_rows_build(&r, m, &cfg, VIEW_DMR);
    CHECK(count_buttons(&r, UA_BM_LINK, NULL) == 3);
    CHECK(count_buttons(&r, UA_BM_DELETE, NULL) == 3);
    b = find_button(&r, UA_BM_LINK, NULL);
    CHECK(b != NULL && strcmp(b->label, "Drop") == 0 && b->a[0] == 91 &&
          b->a[1] == 0 && b->a[2] == 0);
    CHECK(count_buttons(&r, UA_BM_ADD, NULL) == 1);
    CHECK(count_buttons(&r, UA_BM_DROP_QSO, NULL) == 1);

    ui_rows_build(&r, m, &cfg, VIEW_LINKS);
    CHECK(count_buttons(&r, UA_LINK, NULL) == 4);     /* D-Star and YSF x2 */

    ui_rows_build(&r, m, &cfg, VIEW_SYSTEM);
    CHECK(count_buttons(&r, UA_SYS, "reboot") == 1);
    CHECK(count_buttons(&r, UA_SYS, "restart_wpsd_services") == 1);

    /* A paused DMR offers Resume. */
    load_model(m, "repeaterinfo_dmr_paused.html", "radioinfo_idle.html");
    ui_rows_build(&r, m, &cfg, VIEW_STATUS);
    b = find_button(&r, UA_MODE, "DMR");
    CHECK(b != NULL && strcmp(b->label, "Resume") == 0 && b->a[0] == 0);
    CHECK(ui_mode_state(m, "DMR") == PILL_PAUSED);
    CHECK(ui_mode_state(m, "ZZZ") == -1);
    CHECK_STR(ui_pill_value(m, "RPT1"), "M1ABC B");

    /* Connection states. */
    m->conn = -1;
    u_copy(m->conn_msg, sizeof m->conn_msg, "connect: Connection refused");
    ui_rows_build(&r, m, &cfg, VIEW_STATUS);
    CHECK(r.row[1].style == US_BAD);
    CHECK(strstr(r.row[1].col[0], "Connection refused") != NULL);
    CHECK(strstr(r.row[1].col[0], "10.0.0.50") != NULL);
    /* ... and offers the way out when the address has simply changed. */
    CHECK(r.row[2].kind == UR_NOTE && r.row[2].nbtn == 1 &&
          r.row[2].btn[0].action == UA_FIND);
    CHECK(r.row[3].kind == UR_TABS);

    /* While searching, the progress is shown with a Stop button. */
    m->scan_state = 1;
    m->scan_done = 87;
    m->scan_total = 254;
    m->scan_nfound = 1;
    u_copy(m->scan_prefix, sizeof m->scan_prefix, "10.0.0.");
    ui_rows_build(&r, m, &cfg, VIEW_STATUS);
    CHECK(strstr(r.row[1].col[0], "10.0.0.1 - 254") != NULL);
    CHECK(strstr(r.row[1].col[0], "87 of 254 tried, 1 found") != NULL);
    CHECK(r.row[1].nbtn == 1 && r.row[1].btn[0].action == UA_FIND_STOP);
    m->scan_state = 0;

    m->conn = 1;
    m->auth_failed = 1;
    ui_rows_build(&r, m, &cfg, VIEW_STATUS);
    CHECK(r.row[1].style == US_WARN);

    cfg.host[0] = '\0';
    ui_rows_build(&r, m, &cfg, VIEW_STATUS);
    CHECK(strstr(r.row[1].col[0], "No hotspot address") != NULL);

    /* An unrecognised status page: its text is shown, with a warning. */
    load_model(m, "repeaterinfo_basic.html", "radioinfo_idle.html");
    m->status_ok = 0;
    m->status.npill = 0;
    u_copy(m->status_raw, sizeof m->status_raw,
           "Mode Status\nDMR\nEnabled\nNetwork Status");
    ui_rows_build(&r, m, &cfg, VIEW_STATUS);
    {
        int found_warn = 0;
        int found_lines = 0;

        for (v = 0; v < r.n; v++) {
            if (r.row[v].kind == UR_NOTE && r.row[v].style == US_WARN &&
                strstr(r.row[v].col[0], "not in a format") != NULL)
                found_warn = 1;
            if (r.row[v].kind == UR_NOTE &&
                (strcmp(r.row[v].col[0], "Mode Status") == 0 ||
                 strcmp(r.row[v].col[0], "Enabled") == 0 ||
                 strcmp(r.row[v].col[0], "Network Status") == 0))
                found_lines++;
        }

        CHECK(found_warn);
        CHECK(found_lines == 3);
    }
    CHECK(count_buttons(&r, UA_MODE, NULL) == 0);

    /* The System tab shows how each request went. */
    load_model(m, "repeaterinfo_basic.html", "radioinfo_idle.html");
    m->nreq = 2;
    u_copy(m->req_line[0], sizeof m->req_line[0], "Radio: HTTP 200, 1.3 KB - understood");
    u_copy(m->req_line[1], sizeof m->req_line[1], "Status: HTTP 200, 5.5 KB - not understood");
    ui_rows_build(&r, m, &cfg, VIEW_SYSTEM);
    {
        int ok_line = 0;
        int warn_line = 0;

        for (v = 0; v < r.n; v++) {
            if (strcmp(r.row[v].col[0], "Radio: HTTP 200, 1.3 KB - understood") == 0)
                ok_line = (r.row[v].style == US_DIM);
            if (strcmp(r.row[v].col[0], "Status: HTTP 200, 5.5 KB - not understood") == 0)
                warn_line = (r.row[v].style == US_WARN);
        }

        CHECK(ok_line && warn_line);
    }

    /* A hotspot we know nothing about yet still renders. */
    memset(m, 0, sizeof *m);
    u_copy(cfg.host, sizeof cfg.host, "h");
    for (v = 0; v < VIEW_COUNT; v++) {
        ui_rows_build(&r, m, &cfg, (ui_view)v);
        CHECK(r.n >= 3);
    }

    ui_rows_free(&r);
    free(m);
}

static int find_row(const ui_rows *r, const char *col0)
{
    int i;

    for (i = 0; i < r->n; i++) {
        if (strcmp(r->row[i].col[0], col0) == 0)
            return i;
    }

    return -1;
}

static void load_gateway(hs_model *m, const char *status, const char *nets,
                         const char *tgif)
{
    size_t n;
    char *t;

    load_model(m, status, "radioinfo_idle.html");

    t = load(nets, &n);
    m->dmrnet_state = wpsd_parse_dmrnets(t, n, &m->dmrnets) ? 1 : -1;
    free(t);

    t = load(tgif, &n);
    m->tgif_state = wpsd_parse_tgif(t, n, &m->tgif) ? 1 : -1;
    free(t);
}

static void test_rows_dmr_and_links(void)
{
    hs_model *m = (hs_model *)malloc(sizeof *m);
    hs_config cfg;
    ui_rows r;
    const ui_btn *b;
    int i;

    ui_rows_init(&r);
    hs_config_defaults(&cfg);
    u_copy(cfg.host, sizeof cfg.host, "10.0.0.27");

    /* What each tab keeps fresh. */
    CHECK(ui_view_focus(VIEW_HEARD) == HS_R_HEARD);
    CHECK(ui_view_focus(VIEW_DMR) == (HS_R_BM | HS_R_TGIF | HS_R_DMRNET));
    CHECK(ui_view_focus(VIEW_STATUS) == HS_R_HW);
    CHECK(ui_view_focus(VIEW_SYSTEM) == HS_R_HW);
    CHECK(ui_view_focus(VIEW_LINKS) == 0);
    CHECK_STR(ui_view_name(VIEW_DMR), "DMR");

    /* BrandMeister and TGIF side by side, on the DMRGateway. */
    load_gateway(m, "repeaterinfo_gateway.html", "dmr_nets.html",
                 "tgif_links.html");
    ui_rows_build(&r, m, &cfg, VIEW_DMR);

    i = find_row(&r, "DMR networks");
    CHECK(i >= 0 && r.row[i].kind == UR_HEAD);
    CHECK(count_buttons(&r, UA_DMRNET, NULL) == 2);
    b = find_button(&r, UA_DMRNET, "net4");
    CHECK(b != NULL && strcmp(b->label, "Disable") == 0 && b->a[0] == 0);
    b = find_button(&r, UA_DMRNET, "net1");
    CHECK(b != NULL && strcmp(b->label, "Disable") == 0 && b->a[0] == 0);
    i = find_row(&r, "TGIF Network");
    CHECK(i >= 0 && r.row[i].kind == UR_KV && r.row[i].style == US_GOOD);
    CHECK_STR(r.row[i].col[1], "enabled");

    /* BrandMeister's talkgroups are still there. */
    CHECK(count_buttons(&r, UA_BM_LINK, NULL) == 3);

    /* TGIF: this fixture's hotspot is simplex, so one timeslot. */
    CHECK(ui_dmr_slots(m) == 2u);
    i = find_row(&r, "TGIF  2345678");
    CHECK(i >= 0 && r.row[i].kind == UR_HEAD);
    i = find_row(&r, "Timeslot 2");
    CHECK(i >= 0 && r.row[i].style == US_GOOD);
    CHECK_STR(r.row[i].col[1], "TG 91  Worldwide");
    CHECK(find_row(&r, "Timeslot 1") < 0);
    CHECK(r.row[i].nbtn == 2);
    CHECK(r.row[i].btn[0].action == UA_LINK && r.row[i].btn[0].a[0] == PROTO_TGIF &&
          r.row[i].btn[0].a[1] == 1 && r.row[i].btn[0].a[2] == 2);
    CHECK(r.row[i].btn[1].action == UA_LINK && r.row[i].btn[1].a[1] == 0 &&
          r.row[i].btn[1].a[2] == 2);

    /* A network that has been switched off offers Enable, and dims. */
    load_gateway(m, "repeaterinfo_gateway_tgif_off.html",
                 "dmr_nets_tgif_off.html", "tgif_links_none.html");
    ui_rows_build(&r, m, &cfg, VIEW_DMR);
    b = find_button(&r, UA_DMRNET, "net4");
    CHECK(b != NULL && strcmp(b->label, "Enable") == 0 && b->a[0] == 1);
    i = find_row(&r, "TGIF Network");
    CHECK(i >= 0 && r.row[i].style == US_DIM);
    CHECK_STR(r.row[i].col[1], "disabled");
    i = find_row(&r, "Timeslot 2");
    CHECK(i >= 0 && r.row[i].style == US_DIM);
    CHECK_STR(r.row[i].col[1], "not linked");

    /* Both timeslots when the hotspot says both are in use. */
    m->status.pill[m->status.npill].section = 0;
    u_copy(m->status.pill[m->status.npill].label, 40, "TS1");
    m->status.pill[m->status.npill].state = PILL_ACTIVE;
    m->status.npill++;
    CHECK(ui_dmr_slots(m) == 3u);
    ui_rows_build(&r, m, &cfg, VIEW_DMR);
    CHECK(find_row(&r, "Timeslot 1") >= 0 && find_row(&r, "Timeslot 2") >= 0);
    CHECK(count_buttons(&r, UA_LINK, NULL) == 4);

    /* One network only: no manager, no TGIF - just BrandMeister. */
    load_model(m, "repeaterinfo_basic.html", "radioinfo_idle.html");
    m->dmrnet_state = -1;
    m->tgif_state = -1;
    ui_rows_build(&r, m, &cfg, VIEW_DMR);
    CHECK(find_row(&r, "DMR networks") < 0);
    CHECK(count_buttons(&r, UA_DMRNET, NULL) == 0);
    CHECK(count_buttons(&r, UA_LINK, NULL) == 0);
    CHECK(count_buttons(&r, UA_BM_LINK, NULL) == 3);

    /* TGIF set up, but its page of links gave nothing: still linkable. */
    load_gateway(m, "repeaterinfo_gateway.html", "dmr_nets.html",
                 "tgif_links_unused.html");
    ui_rows_build(&r, m, &cfg, VIEW_DMR);
    i = find_row(&r, "TGIF talkgroup");
    CHECK(i >= 0 && r.row[i].nbtn == 2 && r.row[i].btn[0].a[2] == 0);

    /* The login was refused when the manager page was read. */
    m->dmrnet_state = -2;
    ui_rows_build(&r, m, &cfg, VIEW_DMR);
    CHECK(find_row(&r, "DMR networks") >= 0);
    CHECK(count_buttons(&r, UA_DMRNET, NULL) == 0);

    /* DMR paused: say so; DMR not enabled: nothing to manage. */
    load_model(m, "repeaterinfo_dmr_paused.html", "radioinfo_idle.html");
    ui_rows_build(&r, m, &cfg, VIEW_DMR);
    CHECK(strstr(r.row[4].col[0], "DMR is paused") != NULL &&
          r.row[4].style == US_WARN);

    load_model(m, "repeaterinfo_basic.html", "radioinfo_idle.html");
    for (i = 0; i < m->status.npill; i++) {
        if (strcmp(m->status.pill[i].label, "DMR") == 0)
            m->status.pill[i].state = PILL_INACTIVE;
    }
    ui_rows_build(&r, m, &cfg, VIEW_DMR);
    CHECK(count_buttons(&r, UA_BM_LINK, NULL) == 0);
    CHECK(find_row(&r, "DMR is not enabled on this hotspot.") >= 0);

    /* The Links tab says what each mode is linked to. */
    load_model(m, "repeaterinfo_basic.html", "radioinfo_idle.html");
    CHECK_STR(ui_current_link(m, "YSF"), "UK-Calling");
    CHECK_STR(ui_current_link(m, "D-Star"), "REF001 C");
    CHECK(ui_current_link(m, "P25") == NULL);
    ui_rows_build(&r, m, &cfg, VIEW_LINKS);
    i = find_row(&r, "YSF reflector");
    CHECK(i >= 0 && r.row[i].style == US_GOOD);
    CHECK_STR(r.row[i].col[1], "linked to UK-Calling");
    i = find_row(&r, "D-Star reflector");
    CHECK(i >= 0);
    CHECK_STR(r.row[i].col[1], "linked to REF001 C");
    CHECK(count_buttons(&r, UA_LINK_TO, NULL) == 0);        /* none yet */

    /* ... and a paused mode says that instead. */
    load_model(m, "repeaterinfo_dmr_paused.html", "radioinfo_idle.html");
    for (i = 0; i < m->status.npill; i++) {
        if (strcmp(m->status.pill[i].label, "YSF") == 0)
            m->status.pill[i].state = PILL_PAUSED;
    }
    ui_rows_build(&r, m, &cfg, VIEW_LINKS);
    i = find_row(&r, "YSF reflector");
    CHECK(i >= 0 && r.row[i].style == US_WARN);
    CHECK_STR(r.row[i].col[1], "mode paused");

    /* Recently used targets come back as one-click buttons. */
    load_model(m, "repeaterinfo_basic.html", "radioinfo_idle.html");
    hs_mru_push(&cfg, PROTO_YSF, "00001");
    hs_mru_push(&cfg, PROTO_YSF, "FCS00123");
    hs_mru_push(&cfg, PROTO_DSTAR, "XLX123 D");
    ui_rows_build(&r, m, &cfg, VIEW_LINKS);
    CHECK(count_buttons(&r, UA_LINK_TO, NULL) == 3);
    i = find_row(&r, "Recent YSF reflectors:");
    CHECK(i >= 0 && r.row[i].nbtn == 2);
    CHECK_STR(r.row[i].btn[0].label, "FCS00123");           /* newest first */
    CHECK_STR(r.row[i].btn[0].arg, "FCS00123");
    CHECK(r.row[i].btn[0].a[0] == PROTO_YSF);
    CHECK_STR(r.row[i].btn[1].label, "00001");
    i = find_row(&r, "Recent D-Star reflectors:");
    CHECK(i >= 0 && r.row[i].nbtn == 1);
    CHECK_STR(r.row[i].btn[0].arg, "XLX123 D");
    CHECK(r.row[i].btn[0].a[0] == PROTO_DSTAR);

    /* TGIF's recents live on the DMR tab, shown as talkgroup and slot. */
    load_gateway(m, "repeaterinfo_gateway.html", "dmr_nets.html",
                 "tgif_links.html");
    hs_mru_push(&cfg, PROTO_TGIF, "2341/2");
    hs_mru_push(&cfg, PROTO_TGIF, "91/1");
    ui_rows_build(&r, m, &cfg, VIEW_DMR);
    i = find_row(&r, "Recent talkgroups:");
    CHECK(i >= 0 && r.row[i].nbtn == 2);
    CHECK_STR(r.row[i].btn[0].label, "TG 91 TS1");
    CHECK_STR(r.row[i].btn[0].arg, "91/1");
    CHECK_STR(r.row[i].btn[1].label, "TG 2341 TS2");

    {
        char label[24];

        ui_recent_label(PROTO_P25, "10200", label, sizeof label);
        CHECK_STR(label, "TG 10200");
        ui_recent_label(PROTO_NXDN, "65000", label, sizeof label);
        CHECK_STR(label, "TG 65000");
        ui_recent_label(PROTO_TGIF, "2341", label, sizeof label);
        CHECK_STR(label, "TG 2341");
        ui_recent_label(PROTO_YSF, "00001", label, sizeof label);
        CHECK_STR(label, "00001");
        ui_recent_label(PROTO_TGIF, "123456789012345678901/2", label, 24);
        CHECK(strlen(label) < 24);
    }

    ui_rows_free(&r);
    free(m);
}

static void test_recent_targets(void)
{
    hs_config cfg;
    int i;

    hs_config_defaults(&cfg);

    hs_mru_push(&cfg, PROTO_YSF, "A");
    hs_mru_push(&cfg, PROTO_YSF, "B");
    hs_mru_push(&cfg, PROTO_YSF, "C");
    CHECK_STR(cfg.recent[PROTO_YSF][0], "C");
    CHECK_STR(cfg.recent[PROTO_YSF][1], "B");
    CHECK_STR(cfg.recent[PROTO_YSF][2], "A");

    /* The oldest drops off. */
    hs_mru_push(&cfg, PROTO_YSF, "D");
    CHECK_STR(cfg.recent[PROTO_YSF][0], "D");
    CHECK_STR(cfg.recent[PROTO_YSF][2], "B");

    /* One already there moves to the front rather than appearing twice. */
    hs_mru_push(&cfg, PROTO_YSF, "b");
    CHECK_STR(cfg.recent[PROTO_YSF][0], "b");
    CHECK_STR(cfg.recent[PROTO_YSF][1], "D");
    CHECK_STR(cfg.recent[PROTO_YSF][2], "C");
    hs_mru_push(&cfg, PROTO_YSF, "C");
    CHECK_STR(cfg.recent[PROTO_YSF][0], "C");
    CHECK_STR(cfg.recent[PROTO_YSF][1], "b");
    CHECK_STR(cfg.recent[PROTO_YSF][2], "D");
    hs_mru_push(&cfg, PROTO_YSF, "C");
    CHECK_STR(cfg.recent[PROTO_YSF][0], "C");
    CHECK_STR(cfg.recent[PROTO_YSF][1], "b");

    /* Blank, or for a protocol that does not exist: ignored. */
    hs_mru_push(&cfg, PROTO_YSF, "   ");
    hs_mru_push(&cfg, PROTO_YSF, "");
    hs_mru_push(&cfg, PROTO_YSF, NULL);
    hs_mru_push(&cfg, -1, "X");
    hs_mru_push(&cfg, HS_MRU_PROTOS, "X");
    CHECK_STR(cfg.recent[PROTO_YSF][0], "C");

    /* Lists are per protocol, and an over-long target is cut, not overrun. */
    CHECK_STR(cfg.recent[PROTO_P25][0], "");
    hs_mru_push(&cfg, PROTO_P25, "123456789012345678901234567890");
    CHECK(strlen(cfg.recent[PROTO_P25][0]) == HS_MRU_LEN - 1);
    for (i = 0; i < HS_MRU_N; i++)
        CHECK(cfg.recent[PROTO_NXDN][i][0] == '\0');
}

int main(int argc, char **argv)
{
    if (argc < 2) {
        fprintf(stderr, "usage: %s FIXTURE_DIR\n", argv[0]);
        return 2;
    }

    fixture_dir = argv[1];

    test_util();
    test_display_text();
    test_scan_prefix();
    test_html();
    test_json();
    test_status();
    test_radio_hw();
    test_heard();
    test_bm();
    test_tgif_and_networks();
    test_results();
    test_builders();
    test_rows();
    test_rows_dmr_and_links();
    test_recent_targets();

    printf("%d checks, %d failures\n", checks, failures);
    return failures != 0;
}
