/*
 * html.h
 *
 * Just enough HTML handling to read the fragments the WPSD dashboard
 * serves. This is deliberately NOT a general HTML parser: WPSD's pages are
 * generated by PHP templates with a small, regular vocabulary, and the
 * callers below only ever look for specific class names and walk balanced
 * <div> pairs.
 *
 * None of these functions require NUL-terminated input; every range is a
 * [start, end) pair.
 */

#ifndef HS_HTML_H
#define HS_HTML_H

#include <stddef.h>

/* Convert markup to display text: tags are dropped (block-level ones become
 * a space), <script>/<style>/comments are skipped entirely, character
 * entities are decoded, whitespace runs collapse to one space, the result is
 * trimmed and converted to Latin-1. Returns the length stored in `out`. */
size_t html_text(const char *p, size_t n, char *out, size_t cap);

/* Like html_text, but block-level boundaries (</div>, <br>, </tr>, </p>,
 * </li>, headings...) become newlines, so the result keeps the page's rough
 * line structure. Used to show a reply the parsers did not recognise. */
size_t html_lines(const char *p, size_t n, char *out, size_t cap);

/* `p` points at a '<'. Returns a pointer just past the '>' that ends the
 * tag (or past '-->' for a comment), or NULL if it is not closed before
 * `end`. */
const char *html_tag_end(const char *p, const char *end);

/* `p` points just after an opening <div ...>. Returns a pointer to the
 * '<' of the matching </div>, honouring nested divs, or NULL. */
const char *html_div_close(const char *p, const char *end);

/* Find the next "<div" opening tag at or after `p` whose tag text contains
 * `needle` (e.g. a class name). On success returns the pointer to its '<'
 * and stores the end of the tag (just past '>') in *tag_end. */
const char *html_find_div(const char *p, const char *end, const char *needle,
                          const char **tag_end);

/* Same, for any element name (without the '<'), e.g. "span". */
const char *html_find_tag(const char *p, const char *end, const char *name,
                          const char **tag_end);

/* Read the numeric value of attribute `name` (like data-tg="91") inside the
 * tag text [tag, tag_end). Returns 1 and sets *value, else 0. */
int html_attr_int(const char *tag, const char *tag_end, const char *name,
                  int *value);

/* Read the text value of attribute `name` (like data-net-id="net4") inside
 * the tag text [tag, tag_end) into `out`. Returns 1 on success, else 0. */
int html_attr_str(const char *tag, const char *tag_end, const char *name,
                  char *out, size_t cap);

#endif /* HS_HTML_H */
